packages:
  - package
  - example

catalog:
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  react: ^18.2.0
  react-dom: ^18.2.0
  tldraw: ^3.8.0
  '@tldraw/tlschema': ^3.8.0
  typescript: ^5.7.3
